const char INDEX_HTML[] =
"\n"
"<!DOCTYPE html>\n"
"<html>\n"
"\n"
"<head>\n"
"    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\n"
"    <meta name=\"viewport\" content=\"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">\n"
"    <title>ESP8266 Web Form</title>\n"
"    <style>\n"
"        * {\n"
"            padding: 0;\n"
"            margin: 0;\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        /* label text to be aligned to the left */\n"
"        form#wifi-details label {\n"
"            align-self: flex-start;\n"
"        }\n"
"\n"
"        /* common flex styles */\n"
"        .login,\n"
"        .login-card,\n"
"        form#wifi-details,\n"
"        .data-input {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"        }\n"
"\n"
"        .login {\n"
"            background-color: hsl(350, 100%, 88%);\n"
"            height: 100vh;\n"
"            width: 100%;\n"
"\n"
"            font-family: 'Poppins', sans-serif;\n"
"        }\n"
"\n"
"        .login-card {\n"
"            background: rgba(255, 255, 255, 0.75);\n"
"            height: 100vh;\n"
"            width: 33rem;\n"
"            border-radius: 1rem;\n"
"            z-index: 10;\n"
"\n"
"            justify-content: space-evenly;\n"
"        }\n"
"\n"
"        .login-card-heading {\n"
"            font-style: italic;\n"
"            text-transform: capitalize;\n"
"            font-weight: 600;\n"
"        }\n"
"\n"
"        form#wifi-details {\n"
"            height: 55%;\n"
"            justify-content: space-evenly;\n"
"        }\n"
"\n"
"        .data-input {\n"
"            justify-content: flex-start;\n"
"        }\n"
"\n"
"        input {\n"
"            padding: 0 1.5rem;\n"
"            background: #FFFFFF;\n"
"            border: 1px solid #ADADAD;\n"
"            box-sizing: border-box;\n"
"            border-radius: 9px;\n"
"            height: 3rem;\n"
"        }\n"
"\n"
"        button#submit-details {\n"
"            margin: 1rem;\n"
"            height: 3rem;\n"
"            background-color: #2f80ed;\n"
"            box-shadow: 0 4px 19px #80a8de;\n"
"            border-style: none;\n"
"            border-radius: 10px;\n"
"            color: white;\n"
"            width: 12rem;\n"
"            cursor: pointer;\n"
"        }\n"
"\n"
"        .house {\n"
"            position: relative;\n"
"            width: 0px;\n"
"            height: 0px;\n"
"            box-sizing: content-box;\n"
"\n"
"            border-left: 60px solid transparent;\n"
"            border-right: 60px solid transparent;\n"
"            border-bottom: 50px solid hsl(350, 100%, 88%);\n"
"        }\n"
"\n"
"        .house:before,\n"
"        .house:after {\n"
"            content: \"\";\n"
"            box-sizing: content-box;\n"
"            position: absolute;\n"
"            background-color: hsl(350, 100%, 88%);\n"
"        }\n"
"\n"
"        .house:before {\n"
"            width: 10px;\n"
"            height: 30px;\n"
"            top: 20px;\n"
"            left: 30px;\n"
"        }\n"
"\n"
"        .house:after {\n"
"            width: 100px;\n"
"            height: 60px;\n"
"            top: 50px;\n"
"            left: -50px;\n"
"        }\n"
"\n"
"        @media (max-width:768px) {\n"
"            .login {\n"
"                border-radius: 1rem;\n"
"            }\n"
"\n"
"            .login-card {\n"
"                height: 100vh;\n"
"                width: 100%;\n"
"            }\n"
"        }\n"
"\n"
"    </style>\n"
"</head>\n"
"\n"
"<body>\n"
"    <div class=\"login\">\n"
"        <div class=\"login-card\">\n"
"            <div class=\"login-card-heading\">\n"
"                <span>Enter your WiFi credentials</span>\n"
"            </div>\n"
"\n"
"            <div class=\"house\"></div>\n"
"\n"
"            <form id=\"wifi-details\" action=\"/\" method=\"post\">\n"
"                <div class=\"data-input\">\n"
"                    <label for=\"ssid\">SSID</label>\n"
"                    <input id=\"ssid\" type=\"text\" maxlength=\"30\" name=\"ssid\" placeholder=\"SSID\">\n"
"                </div>\n"
"\n"
"                <div class=\"data-input\">\n"
"                    <label for=\"password\">Key</label>\n"
"                    <input id=\"password\" type=\"text\" maxlength=\"30\" name=\"password\" placeholder=\"Password\">\n"
"                </div>\n"
"\n"
"                <div class=\"data-input\">\n"
"                    <button id=\"submit-details\" type=\"submit\">Go</button>\n"
"                </div>\n"
"            </form>\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"\n"
"</html>\n"
"";
